kfm-first-demo/src/main/java/com/kfm/kfmfirstdemo/model/ChartDataItem.java
package com.kfm.kfmfirstdemo.model;

public class ChartDataItem {
    private String name;
    private int value;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }
}

kfm-first-demo/src/main/java/com/kfm/kfmfirstdemo/model/Provice.java
package com.kfm.kfmfirstdemo.model;

public class Provice {
    private int id;
    private String name;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

kfm-first-demo/src/main/java/com/kfm/kfmfirstdemo/model/User.java
package com.kfm.kfmfirstdemo.model;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;

public class User {
    private int id;
    private String name;
    private String idCard;
    private String mob;
    private Provice provice;

    public User() {
    }

    public User(int id) {
        this.id = id;
    }

    public User(String name, String idCard, String mob) {
        this.name = name;
        this.idCard = idCard;
        this.mob = mob;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", idCard='" + idCard + '\'' +
                ", mob='" + mob + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return id == user.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
    public String getSex(){
        return (idCard.charAt(16)%2==1?"男":"女");
    }
    public double getAge(){
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyyMMdd");
        try {
            Date bitrthDay=dateFormat.parse(idCard.substring(6,14));
            long l = new Date().getTime() - bitrthDay.getTime();
            return l/1000/86400/365.25;
        } catch (ParseException e) {
            e.printStackTrace();
        }
        return 0;
    }
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIdCard() {
        return idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public String getMob() {
        return mob;
    }

    public void setMob(String mob) {
        this.mob = mob;
    }

    public Provice getProvice() {
        return provice;
    }

    public void setProvice(Provice provice) {
        this.provice = provice;
    }
}

kfm-first-demo/src/main/java/com/kfm/kfmfirstdemo/controller/IndexController.java
package com.kfm.kfmfirstdemo.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@Controller
//@RestController
public class IndexController {
    @RequestMapping("/")//强制指定了欢迎页面
    public String index(){
        return "redirect:user/showData";//相对地址，不是视图名称
    }
    @RequestMapping(value = "hello")
    @ResponseBody
    public String hello(){
        return "hello1";//跳转的地址
    }
    @RequestMapping("test1")
    public String test1(){
//        /WEB-INF/jsp/ test01 .jsp
        return "test02";
    }
}

kfm-first-demo/src/main/java/com/kfm/kfmfirstdemo/controller/UserController.java
package com.kfm.kfmfirstdemo.controller;

import com.kfm.kfmfirstdemo.model.ChartDataItem;
import com.kfm.kfmfirstdemo.model.User;
import com.kfm.kfmfirstdemo.service.UserService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import javax.annotation.Resource;
import java.util.List;

@Controller
@RequestMapping("user")
public class UserController {
    @Resource
    private UserService userService;
    @RequestMapping(value = "add",method = RequestMethod.GET)
    public ModelAndView add(){
        ModelAndView modelAndView=new ModelAndView();
        modelAndView.setViewName("user/input");
        modelAndView.addObject("act","addSave");
        return modelAndView;
    }
    @RequestMapping(value = "addSave",method = RequestMethod.POST)
    public ModelAndView addSave(User user){
        if (userService.addUser(user)) {
            return list().addObject("message","保存成功");
        }
        ModelAndView modelAndView=new ModelAndView();
        modelAndView.setViewName("user/input");
        modelAndView
                .addObject("act","addSave")
                .addObject("message","保存失败");
//                .addObject("user",user);
        return modelAndView;
    }
    @RequestMapping(value = "delete",method = RequestMethod.GET)
    public ModelAndView delete(User user){
//        userService.deleteUser(new User(id))
        String message=userService.deleteUser(user)?"删除成功":"删除失败";
        return list().addObject("message",message);
    }
//    打开修改页面
    @RequestMapping(value = "update",method = RequestMethod.GET)
    public ModelAndView update(int id){
        ModelAndView modelAndView=new ModelAndView();
        modelAndView.setViewName("user/input");
        User user = userService.getUserById(id);
        modelAndView
            .addObject("act","updateSave")
            .addObject("user",user);
        return modelAndView;
    }
//    修改保存
    @RequestMapping(value = "updateSave",method = RequestMethod.POST)
    public ModelAndView updateSave(User user){
        if (userService.updateUser(user)) {
            return list().addObject("message","保存成功");
        }else{
            ModelAndView modelAndView=new ModelAndView();
            modelAndView.setViewName("user/input");
            modelAndView
                .addObject("act","updateSave")
                .addObject("message","保存失败")
                .addObject("user",user);
            return modelAndView;
        }
    }
//    打开列表页
//    @RequestMapping(value = "list",method = RequestMethod.GET)
    @GetMapping("list")
    public ModelAndView list(){
        ModelAndView modelAndView=new ModelAndView("user/list");
        List<User> users = userService.getUsers();
        modelAndView.addObject("users",users);
        return modelAndView;
    }
    @GetMapping("showData")
    public ModelAndView showData(){
        ModelAndView modelAndView=new ModelAndView("user/showData2");
        return modelAndView;
    }
    @GetMapping("getTotalData")
    @ResponseBody
    public List<ChartDataItem> getTotalData(){
        List<ChartDataItem> chartDataItems=userService.getTotalData();
        return chartDataItems;
    }
}

kfm-first-demo/src/main/webapp/WEB-INF/jsp/nav.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="nav">
    <ul>
        <li>
            用户管理
            <ul>
                <li><a href="user/add">用户录入</a></li>
                <li><a href="user/list">用户信息</a></li>
                <li><a href="user/showData">统计信息</a></li>
            </ul>
        </li>
        <li>信息管理</li>
        <li>推出登录</li>
    </ul>
</div>

kfm-first-demo/src/main/webapp/WEB-INF/jsp/test01.jsp
<%--
  Created by IntelliJ IDEA.
  User: admin
  Date: 2023/5/23
  Time: 11:27
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>test01</title>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        div{
            border: 1px solid black;
        }
        .title{
            height: 100px;

        }
        .midele{
            /*height: calc(100% - 105px);*/
        }
        .nav{
            width: 200px;
            height: 100%;
            float: left;
            background: red;
        }
        .content{
            height: 100%;
            background: yellow;
        }
        .right{
            width: 200px;
            height: 100%;
            float: right;
            background: blue;
        }
    </style>
</head>
<body>
   <div class="title">

   </div>
    <div class="midele">
        <div class="nav">nav</div>
        <div class="right">right</div>
        <div class="content">content</div>
     </div>
</body>
</html>

kfm-first-demo/src/main/webapp/WEB-INF/jsp/test02.jsp
<%--
  Created by IntelliJ IDEA.
  User: admin
  Date: 2023/5/23
  Time: 11:27
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>test01</title>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        div{
            border: 1px solid black;
        }
        .wrap{
            display: flex;/* 弹性布局容器*/
            flex-direction: column;
            height: 100vh;
        }
        .title{
            flex-basis: 100px;
        }
        .midele{
            flex-grow: 1;
            /*background: blue;*/
            display: flex;/* 弹性布局容器*/
            flex-direction: row;
        }
        .nav{
            flex-basis: 200px;
        }
       .right{
            flex-basis: 200px;
        }
       .content{
           flex-grow: 1;
       }
    </style>
</head>
<body>
    <div class="wrap">
       <div class="title">
            aaaa
       </div>
        <div class="midele">
            <div class="nav">nav</div>
            <div class="content">content</div>
            <div class="right">right</div>
         </div>
    </div>
</body>
</html>

kfm-first-demo/src/main/webapp/WEB-INF/jsp/title.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="title">
   <a href="#"><img src="imgs/logo.png" alt="用户信息统计系统"></a>
   <h1>用户信息统计系统</h1>
</div>

kfm-first-demo/src/main/webapp/WEB-INF/jsp/user/input.jsp
<%--
  Created by IntelliJ IDEA.
  User: admin
  Date: 2023/5/23
  Time: 11:27
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>用户信息统计系统</title>
    <base href="${pageContext.request.contextPath}/">
    <link href="style/public.css" rel="stylesheet">
    <style>
        /*@import "";*/
    </style>
</head>
<body>
<div class="wrap">
    <%@include file="../title.jsp" %>
    <div class="midele">
        <%@include file="../nav.jsp" %>
        <div class="content">
            <h2>${act=='addSave'?'用户录入':'修改用户'}</h2>
            <h3>${message}</h3>
            <form action="user/${act}" method="post">
                <table>
                    <tr>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr>
                        <td>姓名</td>
                        <td class="td-left">
                            <input type="hidden" name="id" value="${empty user?0:user.id}">
                            <input type="text" name="name" value="${user.name}">
                        </td>
                    </tr>
                    <tr>
                        <td>身份证号</td>
                        <td class="td-left"><input type="text" name="idCard" value="${user.idCard}"></td>
                    </tr>
                    <tr>
                        <td>联系手机</td>
                        <td class="td-left"><input type="text" name="mob" value="${user.mob}"></td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input class="btn" type="submit" value="保存">
                            <input class="btn" type="reset" value="取消">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>
</body>
</html>

kfm-first-demo/src/main/webapp/WEB-INF/jsp/user/list.jsp
<%--
  Created by IntelliJ IDEA.
  User: admin
  Date: 2023/5/23
  Time: 11:27
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<html>
<head>
    <title>用户信息统计系统</title>
    <base href="${pageContext.request.contextPath}/">
    <link href="style/public.css" rel="stylesheet">
    <style>
        /*@import "";*/
    </style>
</head>
<body>
<div class="wrap">
    <%@include file="../title.jsp" %>
    <div class="midele">
        <%@include file="../nav.jsp" %>
        <div class="content">
            <h2>用户录入</h2>
            <h3>${message}</h3>
            <table>
                <tr>
                    <th>编号</th>
                    <th>姓名</th>
                    <th>身份证号</th>
                    <th>联系手机</th>
                    <th>性别</th>
                    <th>年龄</th>
                    <th>省份</th>
                    <th>删除</th>
                    <th>修改</th>
                </tr>
                <c:forEach var="user" items="${users}">
                    <tr>
                        <td>${user.id}</td>
                        <td>${user.name}</td>
                        <td>${user.idCard}</td>
                        <td>${user.mob}</td>
                        <td>${user.sex}</td>
                        <td><fmt:formatNumber value="${user.age}" pattern="###.#" /></td>
                        <td>${user.provice.name}</td>
                        <td><a href="user/delete?id=${user.id}" onclick="return confirm('真的删除吗？')">删除</a></td>
                        <td><a href="user/update?id=${user.id}">修改</a></td>
                    </tr>
                </c:forEach>
            </table>
        </div>
    </div>
</div>
</body>
</html>

kfm-first-demo/src/main/webapp/WEB-INF/jsp/user/showData.jsp
<%--
  Created by IntelliJ IDEA.
  User: admin
  Date: 2023/5/23
  Time: 11:27
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<html>
<head>
    <title>用户信息统计系统</title>
    <base href="${pageContext.request.contextPath}/">
    <link href="style/public.css" rel="stylesheet">
    <%--   1.CDN引入Echars类库--%>
    <script src="https://cdn.bootcdn.net/ajax/libs/echarts/5.4.2/echarts.js"></script>
</head>
<body>
<div class="wrap">
    <%@include file="../title.jsp" %>
    <div class="midele">
        <%@include file="../nav.jsp" %>
        <div id="main" class="content">
        </div>
    </div>
</div>
</body>
<script>
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));
    //定义配置
    var option = {
        title: {
            text: 'ECharts 入门示例'
        },
        tooltip: {},
        legend: {
            data: ['销量']
        },
        xAxis: {
            data: ['衬衫', '羊毛衫', '雪纺衫', '裤子', '高跟鞋', '袜子']
        },
        yAxis: {},
        series: [
            {
                name: '销量',
                type: 'bar',
                data: [5, 20, 36, 10, 10, 50]
            }
        ]
    };
    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
</script>
</html>

kfm-first-demo/src/main/webapp/WEB-INF/jsp/user/showData1.jsp
<%--
  Created by IntelliJ IDEA.
  User: admin
  Date: 2023/5/23
  Time: 11:27
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<html>
<head>
    <title>用户信息统计系统</title>
    <base href="${pageContext.request.contextPath}/">
    <link href="style/public.css" rel="stylesheet">
    <%--   1.CDN引入Echars类库--%>
    <script src="https://cdn.bootcdn.net/ajax/libs/echarts/5.4.2/echarts.js"></script>
</head>
<body>
<div class="wrap">
    <%@include file="../title.jsp" %>
    <div class="midele">
        <%@include file="../nav.jsp" %>
        <div id="main" class="content">
        </div>
    </div>
</div>
</body>
<script>
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));
    //定义配置
    var option = {
        title: {
            text: '客户分析',
            subtext: '客户所在省份分析',
            left: 'center'
        },
        tooltip: {
            trigger: 'item'
        },
        legend: {
            orient: 'vertical',
            left: 'left'
        },
        series: [
            {
                name: 'Access From',
                type: 'pie',
                radius: '50%',
                data: [
                    { value: 1048, name: 'Search Engine' },
                    { value: 735, name: 'Direct' },
                    { value: 580, name: 'Email' },
                    { value: 484, name: 'Union Ads' },
                    { value: 300, name: 'Video Ads' }
                ],
                emphasis: {
                    itemStyle: {
                        shadowBlur: 10,
                        shadowOffsetX: 0,
                        shadowColor: 'rgba(0, 0, 0, 0.5)'
                    }
                }
            }
        ]
    };


    fetch("user/getTotalData").then((ret)=>{
        // console.log(ret.json());
        return  ret.json();
    }).then((json)=>{
        console.log(json);
        option.series[0].data=json;
        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    }).catch((err)=>{
        console.log(err);
    })
</script>
</html>

kfm-first-demo/src/main/webapp/WEB-INF/jsp/user/showData2.jsp
<%--
  Created by IntelliJ IDEA.
  User: admin
  Date: 2023/5/23
  Time: 11:27
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<html>
<head>
    <title>用户信息统计系统</title>
    <base href="${pageContext.request.contextPath}/">
    <link href="style/public.css" rel="stylesheet">
    <%--   1.CDN引入Echars类库--%>
    <script src="https://cdn.bootcdn.net/ajax/libs/echarts/5.4.2/echarts.js"></script>
    <script src="china.js" ></script>
</head>
<body>
<div class="wrap">
    <%@include file="../title.jsp" %>
    <div class="midele">
        <%@include file="../nav.jsp" %>
        <div id="main" class="content">
        </div>
    </div>
</div>
</body>
<script>
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));
    //定义配置
    let option = {
        backgroundColor: "#E8EFFE",
        title: {
            text: '客户分析',
            subtext: '客户所在省份分析',
            left: 'center'
        },
        geo: {
            type: 'map',
            map: 'china', //chinaMap需要和registerMap中的第一个参数保持一致
            roam: true, // 设置允许缩放以及拖动的效果
            label: {
                show: true  //展示标签
            },
            zoom: 1, //设置初始化的缩放比例
        },

        series: [
            {
                // data: airData,
                geoIndex: 0,  //将空气质量的数据和第0个geo配置关联在一起
                type: 'map',
            }
        ],
        visualMap: {
            min: 0,
            max: 5,
            inRange: {
                color: ['white', '#5475f5'], //控制颜色渐变的范围
            },
            calculable: true //出现滑块
        },
        tooltip: {
            triggerOn: "mousemove",   //mousemove、click
            padding: 8,
            borderWidth: 1,
            borderColor: '#409eff',
            backgroundColor: 'rgba(255,255,255,0.7)',
            textStyle: {
                color: '#000000',
                fontSize: 13
            },
            formatter: function (e, t, n) {
                let data = e.data;
                console.log(data)
                if(e.data==null) return "暂无数据";
                let context = `
                            <div>
                                <p><b style="font-size:15px;">\${data.name}</b></p>
                                <p class="tooltip_style"><span class="tooltip_left">总数</span><span class="tooltip_right">\${data.value}</span></p>
                            </div>
                            `
                return context;
            }
        },
    }
    // 地图注册，第一个参数的名字必须和option.geo.map一致
    echarts.registerMap("china", zhongguo);


    fetch("user/getTotalData").then((ret)=>{
        // console.log(ret.json());
        return  ret.json();
    }).then((json)=>{
        console.log(json);
        option.series[0].data=json;
        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    }).catch((err)=>{
        console.log(err);
    })
</script>
</html>

kfm-first-demo/src/main/webapp/index.jsp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>欢迎</h1>
</body>
</html>